import { DateTicket } from './types';

export const dateTickets: DateTicket[] = [
  {
    id: '1',
    emoji: '🍽️',
    title: 'Cena Romántica',
    description: 'Vale por una cena a la luz de las velas en el restaurante que elijas y no hayamos ido antes (o cena cocinada por el chef Brian).',
    category: 'Romántico',
    image: '/icon/1.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '2',
    emoji: '🧺',
    title: 'Picnic Sorpresa',
    description: 'Un día de sol, bocadillos ricos y naturaleza. Yo me encargo de la cesta.',
    category: 'Aventura',
    image: '/icon/2.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '3',
    emoji: '🎨',
    title: 'Tarde Creativa',
    description: 'Vamos a pintar cerámica, un cuadro o hacer manualidades juntos (con algo rico para tomar, claro).',
    category: 'Aventura',
    image: '/icon/4.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '4',
    emoji: '🍿',
    title: 'Cine y Manta',
    description: 'Maratón de películas y series con palomitas y abrazos ilimitados.',
    category: 'Pareja',
    image: '/icon/3.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '5',
    emoji: '💆‍♀️',
    title: 'Masaje Relajante',
    description: 'Sesión de masaje de cuerpo completo realizado por mí con aceite y música suave.',
    category: 'Romántico',
    image: '/icon/5.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '6',
    emoji: '🧖‍♀️',
    title: 'Spa y Desayuno',
    description: 'Usar los spa que tenemos con las wonderbox y luego desayunar por ahi juntos.',
    category: 'Romántico',
    image: '/icon/23.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '7',
    emoji: '🍳',
    title: 'Desayuno en la Cama',
    description: 'Te despiertas y el desayuno está listo. Tortitas, fruta, café, lo que quieras.',
    category: 'Romántico',
    image: '/icon/6.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '8',
    emoji: '🧩',
    title: 'Escape Room',
    description: 'Ponemos a prueba nuestro equipo resolviendo misterios antes de que se acabe el tiempo.',
    category: 'Aventura',
    image: '/icon/7.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '9',
    emoji: '🍕',
    title: 'Noche de Pizza y Juegos',
    description: 'Pedimos pizza y jugamos a juegos de mesa (o videojuegos) hasta tarde. Me traigo la consola.',
    category: 'Pareja',
    image: '/icon/8.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '10',
    emoji: '🛁',
    title: 'Baño de Espuma',
    description: 'Baño caliente juntos, muchas burbujas y tal vez algo más... Falta la bañera.',
    category: 'Picante',
    image: '/icon/9.png',
    cardLabel: 'Solo para ti...',
  },
  {
    id: '11',
    emoji: '🗺️',
    title: 'Aventura Espontánea',
    description: 'Nos subimos al coche/tren y vamos a un lugar nuevo sin planear nada.',
    category: 'Aventura',
    image: '/icon/10.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '12',
    emoji: '🔭',
    title: 'Ver las Estrellas',
    description: 'Buscamos un sitio oscuro, nos tumbamos y miramos el cielo juntos.',
    category: 'Romántico',
    image: '/icon/11.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '13',
    emoji: '💘',
    title: 'Fantasía Cumplida',
    description: 'Esta noche tú mandas. Elige una fantasía y yo la hago realidad.',
    category: 'Picante',
    image: '/icon/12.png',
    cardLabel: 'Solo para ti...',
  },
  {
    id: '14',
    emoji: '🍫',
    title: 'Cata Privada',
    description: 'Te invito a una cata privada de bombones. Nuestra propia cata dulce en casa.',
    category: 'Aventura',
    image: '/icon/13.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '15',
    emoji: '🏎️',
    title: 'Mario Kart Strip',
    description: 'Jugamos al Mario Kart (o juego que elijas). Quien pierde, se quita una prenda.',
    category: 'Picante',
    image: '/icon/14.png',
    cardLabel: 'Solo para ti...',
  },
  {
    id: '16',
    emoji: '🕺',
    title: 'Clase de Baile',
    description: 'Vamos a una clase de salsa/bachata o ponemos YouTube y hacemos el ridículo juntos en el salón.',
    category: 'Aventura',
    image: '/icon/15.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '17',
    emoji: '⏮️',
    title: 'Recrear 1ª Cita',
    description: 'Volvemos al lugar donde tuvimos nuestra primera cita e intentamos vestirnos igual.',
    category: 'Romántico',
    image: '/icon/16.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '18',
    emoji: '🍩',
    title: 'Postre Sorpresa',
    description: 'El día que tú me digas, aparezco con un postre delicioso por sorpresa.',
    category: 'Romántico',
    image: '/icon/17.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '19',
    emoji: '👂',
    title: 'Soy Todo Oídos',
    description: 'Una hora para que me cuentes lo que quieras (cotilleos, quejas, sueños) y yo solo escucho y te doy la razón.',
    category: 'Pareja',
    image: '/icon/18.png',
    cardLabel: 'Vale por...',
  },
  {
    id: '20',
    emoji: '🍫',
    title: 'Fábrica de Chocolate',
    description: 'Ir a la fabrica de chocolate lindt en suiza.',
    category: 'Aventura',
    image: '/icon/20.png',
    cardLabel: 'Viaje a...',
  },
  {
    id: '21',
    emoji: '🏄‍♂️',
    title: 'Día de Surf',
    description: 'Ir a surfear, que es una de las cosas que quieres hacer.',
    category: 'Aventura',
    image: '/icon/21.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '22',
    emoji: '🧳',
    title: 'Viaje a Japón',
    description: 'Viajar a japon.',
    category: 'Aventura',
    image: '/icon/22.png',
    cardLabel: 'Viaje a...',
  },
  {
    id: '24',
    emoji: '🚗',
    title: 'Autocine',
    description: 'Ir al autocine de autocinestar.',
    category: 'Pareja',
    image: '/icon/24.png',
    cardLabel: 'Plan de...',
  },
  {
    id: '25',
    emoji: '🃏',
    title: 'Comodín Melona',
    description: 'Vale por LO QUE TÚ QUIERAS. Úsalo sabiamente.',
    category: 'Pareja',
    image: '/icon/19.png',
    cardLabel: 'Vale por ...',
  },
];