import { DateTicket } from './types';

export const dateTickets: DateTicket[] = [
  {
    id: '1',
    emoji: '🍽️',
    title: 'Cena Romántica',
    description: 'Vale por una cena a la luz de las velas en el restaurante que elijas y no hayamos ido antes (o cena cocinada por el chef Brian).',
    category: 'Romántico',
    image: '/icon/1.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '2',
    emoji: '🔖',
    title: 'Taller de Marcapáginas',
    description: 'Te diseño y fabrico un marcapáginas único para tus lecturas.',
    category: 'Romántico',
    image: '/icon/32.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '3',
    emoji: '🧺',
    title: 'Picnic Sorpresa',
    description: 'Un día de sol, bocadillos ricos y naturaleza. Yo me encargo de la cesta.',
    category: 'Aventura',
    image: '/icon/2.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '4',
    emoji: '🛍️',
    title: 'Shopping Spree',
    description: 'Nos vamos al centro de Valencia o al centro comercial que elijas. Tú te pruebas, yo opino (y cargo bolsas).',
    category: 'Aventura',
    image: '/icon/33.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '5',
    emoji: '🎨',
    title: 'Tarde Creativa',
    description: 'Vamos a pintar cerámica, un cuadro o hacer manualidades juntos (con algo rico para tomar, claro).',
    category: 'Aventura',
    image: '/icon/4.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '6',
    emoji: '🔥',
    title: 'Operación Entra en Calor',
    description: 'Masaje de pies, calentadores, mantita y chocolate caliente. Prohibido pasar frío. Adiós sabañones.',
    category: 'Relax',
    image: '/icon/35.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '7',
    emoji: '🍿',
    title: 'Cine y Manta',
    description: 'Maratón de películas y series con palomitas y abrazos ilimitados.',
    category: 'Pareja',
    image: '/icon/3.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '8',
    emoji: '👸',
    title: 'Día de la Jefa',
    description: 'Hoy mandas tú. Si me quejo, puedes usar tu carta trampa: "¡Ya lo tienes bien, eh!".',
    category: 'Pareja',
    image: '/icon/34.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '9',
    emoji: '💆‍♀️',
    title: 'Masaje Relajante',
    description: 'Sesión de masaje de cuerpo completo realizado por mí con aceite y música suave.',
    category: 'Romántico',
    image: '/icon/5.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '10',
    emoji: '🌍',
    title: 'Viaje Gastronómico',
    description: 'Elegimos un país al azar y cocinamos (o pedimos) su comida típica.',
    category: 'Aventura',
    image: '/icon/36.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '11',
    emoji: '🧖‍♀️',
    title: 'Spa y Desayuno',
    description: 'Ir otra vez al spa pero esta vez coordinándonos bien y luego a desayunar rico.',
    category: 'Romántico',
    image: '/icon/23.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '12',
    emoji: '🎳',
    title: 'Tarde de Bolera',
    description: 'Vamos a los bolos a ver quien tira más veces la bola por el carril lateral.',
    category: 'Pareja',
    image: '/icon/47.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '13',
    emoji: '🍳',
    title: 'Desayuno en la Cama',
    description: 'Te despiertas y el desayuno está listo. Tortitas, fruta, café, lo que quieras.',
    category: 'Romántico',
    image: '/icon/6.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '14',
    emoji: '📷',
    title: 'Paparazzis del Amor',
    description: 'Salimos a pasear e intentamos sacar fotos chulas (aunque eres mala haciendo fotos, pero te perdono) el uno al otro.',
    category: 'Aventura',
    image: '/icon/37.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '15',
    emoji: '🧩',
    title: 'Escape Room',
    description: 'Ponemos a prueba nuestro equipo resolviendo misterios antes de que se acabe el tiempo.',
    category: 'Aventura',
    image: '/icon/7.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '16',
    emoji: '⛳',
    title: 'Torneo de Minigolf',
    description: '18 hoyos para demostrar quién tiene mejor puntería. El perdedor invita a helado.',
    category: 'Aventura',
    image: '/icon/46.webp',
    cardLabel: 'Reto de...',
  },
  {
    id: '17',
    emoji: '🍕',
    title: 'Noche de Pizza y Juegos',
    description: 'Pedimos pizza y jugamos a juegos de mesa (o videojuegos) hasta tarde. Me traigo la consola.',
    category: 'Pareja',
    image: '/icon/8.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '18',
    emoji: '🕹️',
    title: 'Tarde de Recreativas',
    description: 'Vamos a los recreativos a gastarnos la paga en Air Hockey y máquinas de baile.',
    category: 'Aventura',
    image: '/icon/45.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '19',
    emoji: '🛁',
    title: 'Baño de Espuma',
    description: 'Baño caliente juntos, muchas burbujas y tal vez algo más... Falta la bañera.',
    category: 'Picante',
    image: '/icon/9.webp',
    cardLabel: 'Solo para ti...',
  },
  {
    id: '20',
    emoji: '🧠',
    title: 'Quiz Night',
    description: 'Buscamos un trivial en YouTube/App y competimos. El que pierda hace lo que quiera el otro.',
    category: 'Picante',
    image: '/icon/38.webp',
    cardLabel: 'Reto de...',
  },
  {
    id: '21',
    emoji: '🗺️',
    title: 'Aventura Espontánea',
    description: 'Nos subimos al coche/tren y vamos a un lugar nuevo sin planear nada.',
    category: 'Aventura',
    image: '/icon/10.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '22',
    emoji: '🏎️',
    title: 'Karting',
    description: 'Carrera de Karts. El que pierda paga la cena (o conduce a la vuelta).',
    category: 'Aventura',
    image: '/icon/44.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '23',
    emoji: '🏡',
    title: 'Casa Rural',
    description: 'Alquilar casita rural, tengo varias apuntadas, pero por favor que no haya mucho viento (me asusta).',
    category: 'Romántico',
    image: '/icon/25.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '24',
    emoji: '🚗',
    title: 'Autocine',
    description: 'Ir al autocine a ver una peli, yo llevo las mantas y las palomitas.',
    category: 'Pareja',
    image: '/icon/24.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '25',
    emoji: '🔭',
    title: 'Ver las Estrellas',
    description: 'Buscamos un sitio oscuro, nos tumbamos y miramos el cielo juntos.',
    category: 'Romántico',
    image: '/icon/11.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '26',
    emoji: '💘',
    title: 'Fantasía Cumplida',
    description: 'Esta noche tú mandas. Elige una fantasía y yo la hago realidad.',
    category: 'Picante',
    image: '/icon/12.webp',
    cardLabel: 'Solo para ti...',
  },
  {
    id: '27',
    emoji: '🍫',
    title: 'Cata Privada',
    description: 'Te invito a una cata privada de bombones. Nuestra propia cata dulce en casa.',
    category: 'Aventura',
    image: '/icon/13.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '28',
    emoji: '👨‍🍳',
    title: 'Chefs por un Día',
    description: 'Cocinamos algo nuevo juntos.',
    category: 'Pareja',
    image: '/icon/26.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '29',
    emoji: '🏎️',
    title: 'Mario Kart Strip',
    description: 'Jugamos al Mario Kart (o juego que elijas). Quien pierde, se quita una prenda.',
    category: 'Picante',
    image: '/icon/14.webp',
    cardLabel: 'Reto de...',
  },
  {
    id: '30',
    emoji: '🕺',
    title: 'Clase de Baile',
    description: 'Vamos a una clase de salsa/bachata o ponemos YouTube y hacemos el ridículo juntos en el salón.',
    category: 'Aventura',
    image: '/icon/15.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '31',
    emoji: '⏮️',
    title: 'Recrear 1ª Cita',
    description: 'Volvemos al lugar donde tuvimos nuestra primera cita e intentamos vestirnos igual.',
    category: 'Romántico',
    image: '/icon/16.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '32',
    emoji: '🍩',
    title: 'Postre Sorpresa',
    description: 'El día que tú me digas, aparezco con un postre delicioso sorpresa.',
    category: 'Romántico',
    image: '/icon/17.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '33',
    emoji: '⛸️',
    title: 'Día sobre Hielo',
    description: 'Ir a patinar sobre hielo y quizás encontrarnos un pingüino torpe (yo).',
    category: 'Aventura',
    image: '/icon/27.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '34',
    emoji: '💪',
    title: 'Entreno Juntos',
    description: 'Ir al gimnasio juntos a ponernos fuertes. ¡Tú puedes!',
    category: 'Aventura',
    image: '/icon/29.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '35',
    emoji: '⛰️',
    title: 'Excursión a la Montaña',
    description: 'Nos vamos de ruta un día soleado, bocatas en la mochila y aire puro.',
    category: 'Aventura',
    image: '/icon/31.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '36',
    emoji: '👂',
    title: 'Soy Todo Oídos',
    description: 'Una hora para que me cuentes lo que quieras (cotilleos, quejas, sueños) y yo solo escucho y te doy la razón.',
    category: 'Pareja',
    image: '/icon/18.webp',
    cardLabel: 'Vale por...',
  },
  {
    id: '37',
    emoji: '🍫',
    title: 'Fábrica de Chocolate',
    description: 'Ir a la fabrica de chocolate Lindt en Suiza, pero que no haya mucho viento (me asusta).',
    category: 'Aventura',
    image: '/icon/20.webp',
    cardLabel: 'Viaje a...',
  },
  {
    id: '38',
    emoji: '🏄‍♂️',
    title: 'Día de Surf',
    description: 'Ir a surfear, pero que no haya mucho viento (me asusta).',
    category: 'Aventura',
    image: '/icon/21.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '39',
    emoji: '🧳',
    title: 'Viaje a Japón',
    description: 'Ir a Japón, pero que no haya mucho viento (me asusta).',
    category: 'Aventura',
    image: '/icon/22.webp',
    cardLabel: 'Viaje a...',
  },
  {
    id: '40',
    emoji: '🃏',
    title: 'Comodín Melona',
    description: 'Vale por LO QUE TÚ QUIERAS. Úsalo sabiamente.',
    category: 'Pareja',
    image: '/icon/19.webp',
    cardLabel: 'Vale por ...',
  },
  {
    id: '41',
    emoji: '🎮',
    title: 'Duo Gamer',
    description: 'Nos compramos la Switch. Mario Kart, Animal Crossing y piques asegurados en el sofá.',
    category: 'Futuro',
    image: '/icon/41.webp',
    cardLabel: 'Plan de...',
  },
  {
    id: '42',
    emoji: '🏠',
    title: 'Interioristas Soñadores',
    description: 'Nos sentamos a imaginar y diseñar cómo será nuestra casa en 2 años. ¿Dónde va el sofá?',
    category: 'Futuro',
    image: '/icon/39.webp',
    cardLabel: 'Futuro...',
  },
  {
    id: '43',
    emoji: '🌏',
    title: 'Trotamundos',
    description: 'Viajar por el mundo y rellenar álbumes de fotos hasta que no nos quepan en la estantería.',
    category: 'Futuro',
    image: '/icon/40.webp',
    cardLabel: 'Futuro...',
  },
  {
    id: '44',
    emoji: '🐶',
    title: 'Ampliando Familia',
    description: 'El plan de adoptar a nuestro perro y gato. Porque un hogar necesita pelos en la ropa.',
    category: 'Futuro',
    image: '/icon/42.webp',
    cardLabel: 'Futuro...',
  },
  {
    id: '45',
    emoji: '💍',
    title: 'Boda',
    description: 'Nos casamos. Vivimos felices y comemos perdices.',
    category: 'Pareja',
    image: '/icon/30.webp',
    cardLabel: 'Futuro...',
  },
];